// export enum Region {
//   US = 'US',
//   BY = 'BY',
//   TJ = 'TJ',
//   TM = 'TM',
//   KZ = 'KZ',
//   GB = 'GB',
//   DE = 'DE',
//   ES = 'ES',
//   FR = 'FR',
//   UZ = 'UZ',
//   KG = 'KG',
//   MD = 'MD',
//   AC = 'AC',
//   AD = 'AD',
//   AF = 'AF',
//   AG = 'AG',
//   AI = 'AI',
//   AL = 'AL',
//   AM = 'AM',
//   AO = 'AO',
//   AQ = 'AQ',
//   AS = 'AS',
//   AU = 'AU',
//   AW = 'AW',
//   AX = 'AX',
//   BA = 'BA',
//   BB = 'BB',
//   BD = 'BD',
//   BF = 'BF',
//   BG = 'BG',
//   BI = 'BI',
//   BJ = 'BJ',
//   BL = 'BL',
//   BM = 'BM',
//   BN = 'BN',
//   BQ = 'BQ',
//   BS = 'BS',
//   BT = 'BT',
//   BV = 'BV',
//   BW = 'BW',
//   BZ = 'BZ',
//   CA = 'CA',
//   CC = 'CC',
//   CD = 'CD',
//   CF = 'CF',
//   CG = 'CG',
//   CI = 'CI',
//   CK = 'CK',
//   CM = 'CM',
//   CN = 'CN',
//   CS = 'CS',
//   CU = 'CU',
//   CV = 'CV',
//   CW = 'CW',
//   CX = 'CX',
//   CY = 'CY',
//   DK = 'DK',
//   DM = 'DM',
//   DR = 'DR',
//   EA = 'EA',
//   EE = 'EE',
//   EH = 'EH',
//   EN = 'EN',
//   ET = 'ET',
//   FJ = 'FJ',
//   FK = 'FK',
//   FM = 'FM',
//   FO = 'FO',
//   GA = 'GA',
//   GD = 'GD',
//   GE = 'GE',
//   GF = 'GF',
//   GG = 'GG',
//   GH = 'GH',
//   GI = 'GI',
//   GL = 'GL',
//   GN = 'GN',
//   GP = 'GP',
//   GQ = 'GQ',
//   GS = 'GS',
//   GU = 'GU',
//   GW = 'GW',
//   GY = 'GY',
//   HK = 'HK',
//   HR = 'HR',
//   HT = 'HT',
//   IC = 'IC',
//   IE = 'IE',
//   IL = 'IL',
//   IM = 'IM',
//   IN = 'IN',
//   IO = 'IO',
//   IS = 'IS',
//   JE = 'JE',
//   KE = 'KE',
//   KH = 'KH',
//   KI = 'KI',
//   KN = 'KN',
//   KY = 'KY',
//   LA = 'LA',
//   LC = 'LC',
//   LI = 'LI',
//   LK = 'LK',
//   LR = 'LR',
//   LS = 'LS',
//   LU = 'LU',
//   LV = 'LV',
//   MC = 'MC',
//   ME = 'ME',
//   MF = 'MF',
//   MG = 'MG',
//   MH = 'MH',
//   MK = 'MK',
//   ML = 'ML',
//   MM = 'MM',
//   MN = 'MN',
//   MO = 'MO',
//   MP = 'MP',
//   MQ = 'MQ',
//   MS = 'MS',
//   MT = 'MT',
//   MU = 'MU',
//   MV = 'MV',
//   MW = 'MW',
//   MZ = 'MZ',
//   NA = 'NA',
//   NC = 'NC',
//   NE = 'NE',
//   NF = 'NF',
//   NG = 'NG',
//   NJ = 'NJ',
//   NO = 'NO',
//   NR = 'NR',
//   NU = 'NU',
//   NZ = 'NZ',
//   PF = 'PF',
//   PG = 'PG',
//   PK = 'PK',
//   PM = 'PM',
//   PN = 'PN',
//   PR = 'PR',
//   PW = 'PW',
//   QS = 'QS',
//   RE = 'RE',
//   RW = 'RW',
//   SB = 'SB',
//   SC = 'SC',
//   SH = 'SH',
//   SI = 'SI',
//   SJ = 'SJ',
//   SL = 'SL',
//   SM = 'SM',
//   SN = 'SN',
//   SR = 'SR',
//   ST = 'ST',
//   SX = 'SX',
//   SZ = 'SZ',
//   TC = 'TC',
//   TF = 'TF',
//   TG = 'TG',
//   TK = 'TK',
//   TL = 'TL',
//   TO = 'TO',
//   TP = 'TP',
//   TS = 'TS',
//   TV = 'TV',
//   TZ = 'TZ',
//   UG = 'UG',
//   UM = 'UM',
//   VA = 'VA',
//   VC = 'VC',
//   VG = 'VG',
//   VI = 'VI',
//   VU = 'VU',
//   WF = 'WF',
//   WS = 'WS',
//   XA = 'XA',
//   XB = 'XB',
//   XK = 'XK',
//   XX = 'XX',
//   YJ = 'YJ',
//   YT = 'YT',
//   ZA = 'ZA',
//   ZG = 'ZG',
//   ZM = 'ZM',
//   ZN = 'ZN',
//   ZW = 'ZW',
//   ZZ = 'ZZ',
//   TR = 'TR',
//   AZ = 'AZ',
//   MA = 'MA',
//   LB = 'LB',
//   DZ = 'DZ',
//   ER = 'ER',
//   TN = 'TN',
//   SS = 'SS',
//   BR = 'BR',
//   MX = 'MX',
//   TH = 'TH',
//   ID = 'ID',
//   MY = 'MY',
//   VN = 'VN',
//   PH = 'PH',
//   SG = 'SG',
//   KR = 'KR',
//   JP = 'JP',
//   EG = 'EG',
//   SY = 'SY',
//   PS = 'PS',
//   JO = 'JO',
//   IQ = 'IQ',
//   DJ = 'DJ',
//   KM = 'KM',
//   SO = 'SO',
//   TD = 'TD',
//   OM = 'OM',
//   QA = 'QA',
//   KW = 'KW',
//   AE = 'AE',
//   BH = 'BH',
//   SA = 'SA',
//   YE = 'YE',
//   LY = 'LY',
//   SD = 'SD',
//   MR = 'MR',
//   LT = 'LT',
//   JM = 'JM',
//   CH = 'CH',
//   IR = 'IR',
//   AN = 'AN',
//   FI = 'FI',
//   PY = 'PY',
//   AR = 'AR',
//   GR = 'GR',
//   UY = 'UY',
//   CR = 'CR',
//   DO = 'DO',
//   PE = 'PE',
//   IT = 'IT',
//   TT = 'TT',
//   SV = 'SV',
//   CZ = 'CZ',
//   BE = 'BE',
//   CO = 'CO',
//   TW = 'TW',
//   HN = 'HN',
//   EC = 'EC',
//   SK = 'SK',
//   NP = 'NP',
//   // RS = 'RS',
//   RU = 'RU',
//   NI = 'NI',
//   SE = 'SE',
//   GT = 'GT',
//   CL = 'CL',
//   NL = 'NL',
//   RO = 'RO',
//   HU = 'HU',
//   VE = 'VE',
//   AT = 'AT',
//   PL = 'PL',
//   PA = 'PA',
//   BO = 'BO',
//   GM = 'GM',
//   PT = 'PT',
// }

export enum Region {
  AE = 'AE', // 阿联酋
  AF = 'AF', // 阿富汗
  AG = 'AG', // 安提瓜和巴布达
  AI = 'AI', // 安圭拉
  AL = 'AL', // 阿尔巴尼亚
  AM = 'AM', // 亚美尼亚
  AO = 'AO', // 安哥拉
  AR = 'AR', // 阿根廷
  AT = 'AT', // 奥地利
  AU = 'AU', // 澳大利亚
  AZ = 'AZ', // 阿塞拜疆
  BB = 'BB', // 巴巴多斯
  BD = 'BD', // 孟加拉国
  BE = 'BE', // 比利时
  BF = 'BF', // 布基纳法索
  BG = 'BG', // 保加利亚
  BH = 'BH', // 巴林
  BI = 'BI', // 布隆迪
  BJ = 'BJ', // 贝宁
  BM = 'BM', // 百慕大
  BN = 'BN', // 文莱
  BO = 'BO', // 玻利维亚
  BR = 'BR', // 巴西
  BS = 'BS', // 巴哈马
  BW = 'BW', // 博茨瓦纳
  BY = 'BY', // 白俄罗斯
  BZ = 'BZ', // 伯利兹
  CA = 'CA', // 加拿大
  CF = 'CF', // 中非共和国
  CG = 'CG', // 刚果
  CH = 'CH', // 瑞士
  CK = 'CK', // 库克群岛
  CL = 'CL', // 智利
  CM = 'CM', // 喀麦隆
  CN = 'CN', // 中国
  CO = 'CO', // 哥伦比亚
  CR = 'CR', // 哥斯达黎加
  CU = 'CU', // 古巴
  CY = 'CY', // 塞浦路斯
  CZ = 'CZ', // 捷克
  DE = 'DE', // 德国
  DJ = 'DJ', // 吉布提
  DK = 'DK', // 丹麦
  DO = 'DO', // 多米尼加
  DZ = 'DZ', // 阿尔及利亚
  EC = 'EC', // 厄瓜多尔
  EE = 'EE', // 爱沙尼亚
  EG = 'EG', // 埃及
  ES = 'ES', // 西班牙
  ET = 'ET', // 埃塞俄比亚
  FI = 'FI', // 芬兰
  FJ = 'FJ', // 斐济
  FR = 'FR', // 法国
  GA = 'GA', // 加蓬
  GB = 'GB', // 英国
  GD = 'GD', // 格林纳达
  GE = 'GE', // 格鲁吉亚
  GH = 'GH', // 加纳
  GI = 'GI', // 直布罗陀
  GM = 'GM', // 冈比亚
  GN = 'GN', // 几内亚
  GR = 'GR', // 希腊
  GT = 'GT', // 危地马拉
  GU = 'GU', // 关岛
  GY = 'GY', // 圭亚那
  HK = 'HK', // 香港
  HN = 'HN', // 洪都拉斯
  HT = 'HT', // 海地
  HU = 'HU', // 匈牙利
  ID = 'ID', // 印度尼西亚
  IE = 'IE', // 爱尔兰
  IL = 'IL', // 以色列
  IN = 'IN', // 印度
  IQ = 'IQ', // 伊拉克
  IR = 'IR', // 伊朗
  IS = 'IS', // 冰岛
  IT = 'IT', // 意大利
  JM = 'JM', // 牙买加
  JO = 'JO', // 约旦
  JP = 'JP', // 日本
  KE = 'KE', // 肯尼亚
  KG = 'KG', // 吉尔吉斯斯坦
  KH = 'KH', // 柬埔寨
  KP = 'KP', // 朝鲜
  KR = 'KR', // 韩国
  KW = 'KW', // 科威特
  KZ = 'KZ', // 哈萨克斯坦
  LA = 'LA', // 老挝
  LB = 'LB', // 黎巴嫩
  LC = 'LC', // 圣卢西亚
  LI = 'LI', // 列支敦士登
  LK = 'LK', // 斯里兰卡
  LR = 'LR', // 利比里亚
  LS = 'LS', // 莱索托
  LT = 'LT', // 立陶宛
  LU = 'LU', // 卢森堡
  LV = 'LV', // 拉脱维亚
  LY = 'LY', // 利比亚
  MA = 'MA', // 摩洛哥
  MC = 'MC', // 摩纳哥
  MD = 'MD', // 摩尔多瓦
  MG = 'MG', // 马达加斯加
  ML = 'ML', // 马里
  MM = 'MM', // 缅甸
  MN = 'MN', // 蒙古
  MO = 'MO', // 澳门
  MT = 'MT', // 马耳他
  MU = 'MU', // 毛里求斯
  MV = 'MV', // 马尔代夫
  MW = 'MW', // 马拉维
  MX = 'MX', // 墨西哥
  MY = 'MY', // 马来西亚
  MZ = 'MZ', // 莫桑比克
  NA = 'NA', // 纳米比亚
  NE = 'NE', // 尼日尔
  NG = 'NG', // 尼日利亚
  NI = 'NI', // 尼加拉瓜
  NL = 'NL', // 荷兰
  NO = 'NO', // 挪威
  NP = 'NP', // 尼泊尔
  NR = 'NR', // 瑙鲁
  NZ = 'NZ', // 新西兰
  OM = 'OM', // 阿曼
  PA = 'PA', // 巴拿马
  PE = 'PE', // 秘鲁
  PG = 'PG', // 巴布亚新几内亚
  PH = 'PH', // 菲律宾
  PK = 'PK', // 巴基斯坦
  PL = 'PL', // 波兰
  PR = 'PR', // 波多黎各
  PT = 'PT', // 葡萄牙
  PY = 'PY', // 巴拉圭
  QA = 'QA', // 卡塔尔
  RO = 'RO', // 罗马尼亚
  RU = 'RU', // 俄罗斯
  SA = 'SA', // 沙特阿拉伯
  SB = 'SB', // 所罗门群岛
  SC = 'SC', // 塞舌尔
  SD = 'SD', // 苏丹
  SE = 'SE', // 瑞典
  SG = 'SG', // 新加坡
  SI = 'SI', // 斯洛文尼亚
  SK = 'SK', // 斯洛伐克
  SL = 'SL', // 塞拉利昂
  SN = 'SN', // 塞内加尔
  SO = 'SO', // 索马里
  SR = 'SR', // 苏里南
  SV = 'SV', // 萨尔瓦多
  SY = 'SY', // 叙利亚
  SZ = 'SZ', // 斯威士兰
  TD = 'TD', // 乍得
  TG = 'TG', // 多哥
  TH = 'TH', // 泰国
  TJ = 'TJ', // 塔吉克斯坦
  TM = 'TM', // 土库曼斯坦
  TN = 'TN', // 突尼斯
  TO = 'TO', // 汤加
  TR = 'TR', // 土耳其
  TT = 'TT', // 特立尼达和多巴哥
  TW = 'TW', // 台湾
  TZ = 'TZ', // 坦桑尼亚
  UA = 'UA', // 乌克兰
  UG = 'UG', // 乌干达
  US = 'US', // 美国
  UY = 'UY', // 乌拉圭
  UZ = 'UZ', // 乌兹别克斯坦
  VC = 'VC', // 圣文森特
  VE = 'VE', // 委内瑞拉
  VN = 'VN', // 越南
  YE = 'YE', // 也门
  ZA = 'ZA', // 南非
  ZM = 'ZM', // 赞比亚
  ZW = 'ZW', // 津巴布韦

  HR = 'HR', // 克罗地亚
}

export const DefaultRegion = Region.US;
