# 排除所有apps目录，除了server
apps/*
!apps/main-web

# 排除不需要的packages
packages/database
packages/play
packages/node-shared

# 排除所有node_modules
**/node_modules

# 排除其他不需要的文件
.git
.gitignore
.DS_Store
**/*.log

**/dist
**/dist-ssr

**/*.bak
**/backup

**/docker-images

**/.rollup.cache

**/*.tsbuildinfo
