services:
  redis:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_MEMORY_LIMIT=${REDIS_MEMORY_LIMIT}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - redis_data:/data
    ports:
      - '${REDIS_PORT}:6379'
    # deploy:
    #   resources:
    #     limits:
    #       memory: ${REDIS_MEMORY_LIMIT}
volumes:
  redis_data:
    external: true
    name: ${VOLUME_NAME}
